# ┌────────────────────────────────────────────────────────────────────────────+
# │ PXInviteTicket 콘피그 파일입니다.
# │ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요.
# └────────────────────────────────────────────────────────────────────────────+

InviteTicket:
  #이 플러그인의 기능을 활성화할 것인지 조정합니다
  EnablePlugin: true

InviteSetting:
  #유저 한명당 초대 가능한 플레이어 개수를 설정합니다.
  InviteLimit: 5

  #초대되지 않은 플레이어가 접속할떄 보이는 메세지
  kick_message: "초대를 받지 않아서 입장할 수 없습니다."