name: PXInviteTicket
version: '${version}'
main: com.github.luriel0228.pxinviteticket.PXInviteTicket
api-version: '1.20'
config: config.yml
commands:
  초대:
    description: 초대권 시스템
  invite:
    description: 초대권 시스템 영어
  it:
    description: 초대권 시스템 영어 축약
permissions:
  px.inviteticket.reload:
    default: op
  px.inviteticket.admin:
    default: op
  px.inviteticket.bypass:
    default: op